#!/usr/bin/env python3
"""orient.json — full orientation in ONE fetch.

A cold agent GETs /orient.json and holds: the current tick anchor, the newest world
frame, every registered dimension, and the chant table. Regenerated by every beat.
"""
import json, sys, pathlib, datetime, hashlib

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import chainio

ROOT = pathlib.Path(__file__).resolve().parent.parent

def utc():
    n = datetime.datetime.now(datetime.timezone.utc)
    return n.strftime("%Y-%m-%dT%H:%M:%S.") + f"{n.microsecond // 1000:03d}Z"

def head_and_latest(d):
    meta = json.loads((ROOT / d / "HEAD.json").read_text())
    latest = json.loads((ROOT / d / f"{meta['count']-1}.json").read_text())
    return meta, latest

def main():
    ticks_meta, tick = head_and_latest("ticks")
    world_meta, world = head_and_latest("world")
    reg = chainio.load_chain(ROOT / "registry")
    dims = [f["payload"] for f in reg if f["kind"] == "registry.dimension"]
    chants = {}
    cdir = ROOT / "chants"
    if cdir.is_dir():
        for p in sorted(cdir.glob("*.chant.json")):
            c = json.loads(p.read_text())
            chants[c["streams"][0]] = c["incantation"]
    out = {"schema": "dogg/0-orient", "generated_utc": utc(),
           "protocol": "https://github.com/kody-w/dogg/blob/main/PROTOCOL.md",
           "tick": {"seq": tick["seq"], "frame_hash": tick["frame_hash"], "utc": tick["utc"]},
           "world": {"frame_hash": world["frame_hash"], "seq": world["seq"],
                     "data": world["payload"].get("world", {})},
           "dimensions": dims, "chants": chants}
    (ROOT / "orient.json").write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    print(f"orient.json: tick {tick['seq']}, {len(dims)} dimensions, {len(chants)} chants")

if __name__ == "__main__":
    main()
